Feat/add components
tecsinapse/design-system pull request #1
Opened 2021-05-03 16:05 UTC by ryancarloscorrea

Adição de componentes básicos.
Card, Button, Badge, RadioButton, Paper Text, Switch, Input, CheckBox

2021-05-03 18:13 UTC, dennervidal requested changes

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Badge/Badge.tsx
> +      <TextStyle>Badge</TextStyle>
o conteúdo será via children e o theme é uma prop interna

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Card/Card.tsx
> +  );
temos que pensar em mecanismos de CardHeader, CardContent e CardFooter, também será via children.

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/CheckBox/CheckBox.tsx
> +export const CheckBox = ({ label }: CheckBoxProps): JSX.Element => {
Acho que é melhor Checkbox, com b minusculo

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Paper/Paper.tsx
> +  style?: any;
esse style precisamos testar se precisa estar na interface, creio que não, mas precisa passar pra baixo

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Paper/Paper.tsx
> +  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
ai o style precisa chegar aqui
`${({ style }) => style}`

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Switch/Switch.tsx
> +  const toggleSwitch = () => setIsEnabled(previousState => !previousState);
precisa externalizar o controle do switch pro usuário, exemplo:
```
const { onChange, active } = props;

const handleChange = (value) => {
  onChange(value);
}

return ( 
  <...
    onValueChange={handleChange}
    value={active}
```

2021-05-03 18:13 UTC, dennervidal commented on packages/react-core/src/components/atoms/Text/Text.tsx
> +  ${({ style }) => style}
é assim que todo lugar que vai receber o style de cima vai ser, só precisa validar mesmo a interface.

2021-05-03 20:03 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/CheckBox/CheckBox.tsx
> +export const CheckBox = ({ label }: CheckBoxProps): JSX.Element => {
Resolvido

2021-05-04 15:41 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Paper/Paper.tsx
> +  box-shadow: 0 4px 8px rgba(0, 0, 0, 0.4);
Resolvido.

2021-05-04 15:42 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Text/Text.tsx
> +  ${({ style }) => style}
Resolvido.

2021-05-04 15:45 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Card/Card.tsx
> +  );
Parte do children feita.

2021-05-05 15:04 UTC, agnaldocitadin commented on packages/react-core/src/components/atoms/Button/styled.ts
>    ${({ style }) => style}
Aqui também, o style não é herdado automaticamente do styled?

2021-05-05 15:05 UTC, agnaldocitadin commented on packages/react-core/src/components/atoms/Checkbox/styled.ts
> +import { Text } from '../Text/index';
acho que não precisa declarar o "index" nesse caso.

2021-05-05 15:10 UTC, agnaldocitadin commented on packages/react-core/src/components/atoms/Badge/Badge.tsx
> +  style?: ClassNamesProps;
Como a base do Badge é uma View, acho que se tipar o style com ViewStyle já vai autocompletar as props de style da view, não?

2021-05-05 15:18 UTC, agnaldocitadin commented on packages/react-core/src/components/RadioButton/RadioButton.tsx
> +  options: Array<string>;
Não é melhor tipar o array ao invés de ser sempre string? Me parece limitar sempre valores em string.

2021-05-06 15:32 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Card/Card.tsx
> +  );
Componentes auxiliares criados.

2021-05-06 15:47 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Text/styled.ts
>    ${({ style }) => style}
Caso chegue algum estilo ao componente, este será usado juntamente com os estilos anteriores.

2021-05-06 15:47 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Button/styled.ts
>    ${({ style }) => style}
Aparentemente não é herdado automaticamente, nos testes que eu e o Denner fizemos, só assim funcionou.

2021-05-06 15:47 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Checkbox/styled.ts
> +import { Text } from '../Text/index';
Realmente não precisa, já alterei aqui.

2021-05-06 15:48 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Badge/Badge.tsx
> +  style?: ClassNamesProps;
Irei testar.

2021-05-06 15:48 UTC, ryancarloscorrea commented on packages/react-core/src/components/RadioButton/RadioButton.tsx
> +  options: Array<string>;
Faz sentido, vou precisar refatorar todo código do RadioButton, irei tipar dessa forma.

2021-05-06 18:25 UTC, dennervidal commented
branch sync

2021-05-06 18:25 UTC, merged