feat(#174139): Icon text button
tecsinapse/design-system pull request #125
Opened 2022-08-18 14:59 UTC by lucaspr98

2022-08-18 17:20 UTC, dennervidal requested changes

2022-08-18 17:20 UTC, dennervidal commented on packages/react-native-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +  const iconComponent = useMemo(
não seria melhor separar esse aqui e o proximo em subcomponentes dentro do icontextbtn?

2022-08-18 17:20 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.stories.tsx
> +  title: 'Hybrid/IconTextButton',
Se as implementações são distintas e vc já criou no nativo, recomendo indicar que ele é "Web"

2022-08-18 17:20 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +  const iconComponent = useMemo(
o mesmo aqui vale pro comentario do nativo

2022-08-18 17:20 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +      onMouseOut={() => setHover(true)}
eu usaria useCallback aqui

2022-08-18 17:21 UTC, gitTecsinapse commented
https://tecsinapse.tpondemand.com/entity/174139

2022-08-18 18:49 UTC, dennervidal requested changes

2022-08-18 18:49 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +      {iconPosition === 'left' ? iconComponent : <></>}
passa o jsx direto aqui ao invés de criar uma variavel

isso vale pra todas as ocorrencias

2022-08-18 18:54 UTC, lucaspr98 commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +      {iconPosition === 'left' ? iconComponent : <></>}
no caso do iconComponent não vai ficar ruim os dois componentes iguais duplicados? Dependendo se a posição é left ou right

2022-08-18 18:58 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +      {iconPosition === 'left' ? iconComponent : <></>}
é, nesse caso sim, ah não ser que voce passe a responsabilidade pro icon, mas ai vai inchar a assinatura dele

2022-08-18 18:58 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/IconTextButton/IconTextButton.tsx
> +      {iconPosition === 'left' ? iconComponent : <></>}
mas só de ter extraído já ta bem melhor :)

2022-08-22 12:51 UTC, dennervidal approved these changes

2022-08-22 12:51 UTC, merged