Ts 1082 adaptar displaymultivalue select
tecsinapse/design-system pull request #156
Opened 2023-08-14 19:30 UTC by btrzdev

2023-08-14 20:31 UTC, ryancarloscorrea requested changes

2023-08-14 20:31 UTC, ryancarloscorrea commented on packages/react-web-kit/src/components/molecules/Select/Select.tsx
> +  const multipleValueCount =
Achei confuso esses ternários concatenedos.
Uma função que retornasse essa label ficaria melhor.
Ex: getLabel(valueLength: number, optionsLength) => {
  if(valueLength === 1) return '....'
  if(valueLength > 1 && valueLength < optionsLength) return ....
  if (valueLength === optionsLength)
}


Me parece que esse 'Nenhum item selecionado' não vai precisa ser utilizada, pois nesse caso, a gente vai exibir o placeholder/label

2023-08-15 13:35 UTC, dennervidal requested changes
considerações

2023-08-15 13:35 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/Select/Select.tsx
> +  const multipleValueCount =
Vamos utilizar o seguinte padrão:

- Nenhum item selecionado: mantém comportamento de exibir label/placeholder
- 1 item selecionado: mantém comportamento de mostrar label do valor selecionado
- N itens selecionados: exibe a label com a quantidade de elementos selecionados, se todos, exibir `Todos` e não a quantidade

outra consideração, acredito que é melhor vc substituir a parte de tratamento múltiplo na função `displayValue`, já que não seria necessário mexer no arquivo do componente e a lógica já fica centralizada no local adequado

2023-08-16 14:27 UTC, dennervidal approved these changes

2023-08-16 19:15 UTC, merged