Added Select Component to react-native-kit
tecsinapse/design-system pull request #16
Opened 2021-06-22 20:26 UTC by heliohfs

2021-06-23 13:10 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +          renderItem={item => (
se der desestrutura aqui antes, pra não ficar `item.item`

2021-06-23 13:15 UTC, dennervidal commented
resolver conflito antes do merge

2021-06-24 17:59 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +            <ListItem onPress={handlePressItem(keyExtractor(item, index))}>
estive falando com o @agnaldocitadin e pensamos que talvez esse wrapper `<ListItem />` pode ser um componente exportável do Select. Estamos pensando em cenários onde iremos trazer paginação infinita. Já existe um componente no dynamo-app que é uma FlatList com essa funcionalidade, então talvez seja interessante termos uma property pra passar uma função que retorna um elemento customizado de Lista, o que seria mais ou menos assim:

```
...
{searchBar && <SearchBarContainer>{searchBar}</SearchBarContainer>}
{customListRenderer? customListRenderer(data) : <FlatList />}
...
```
Voltando ao Wrapper do ListItem, o dev poderia reusar na sua lista custom, dentro do renderItem.

2021-06-24 17:59 UTC, dennervidal commented on packages/kitchensink-app/storybook/stories/Select/Select.stories.tsx
> +const searchBar = (<Input placeholder={"Busque a opção desejada"}/>)
No searchBar, acho que seria melhor levar isso pra dentro do componente, já que não temos previsto outras formas de buscar dados.

2021-06-24 17:59 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +        <Header>
Seria possivel extrair o header como um componente global?

O Header pode adotar um padding em todas as laterais de 16px (deca), ocupando 100% da view horizontalmente. A altura pode ser definida pelo tamanho de seus filhos, o que provavelmente seria um flex container.

2021-06-28 15:30 UTC, heliohfs commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +            <ListItem onPress={handlePressItem(keyExtractor(item, index))}>
Conforme alinhamos hoje, temos as seguintes opções por enquanto:

- Utilizar o InfiniteFlatList no próprio Select;
- Implementar o Select no InfiniteFlatList;
- Implementar a paginação infinita utilizando ScrollView para ser repassado ao renderScrollComponent da FlatList do Select;
- Tornar o modal acoplável, deixando o Select a cargo apenas de renderizar as opções selecionadas e controlar o press do usuário; ou
- Utilizar um HOC que decida entre utilizar ou o Select pronto ou o Select com modal acoplável.

2021-06-28 19:44 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +            <ListItem onPress={handlePressItem(keyExtractor(item, index))}>
@nilson-antonio @agnaldocitadin @ryancarloscorrea temos que discutir sobre as opções

2021-06-30 16:48 UTC, agnaldocitadin commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +            <ListItem onPress={handlePressItem(keyExtractor(item, index))}>
Como havia sugerido, melhor deixar isso de lado por enquanto e quando tivermos um caso mais concreto de uso, podemos voltar a avaliar as opções.

2021-06-30 16:58 UTC, agnaldocitadin commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
>  const Component = <Data, Type extends 'single' | 'multi'>({
Apenas por questões de padronização, estamos tipando com componentes com a interface FC do React, funcionalmente não traz diferença, mas ele já disponibiliza a property children por padrão.

2021-07-05 13:44 UTC, heliohfs commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
>  const Component = <Data, Type extends 'single' | 'multi'>({
Neste caso tive que aproveitar o type inference do TS, pois não é possível repassar os generics necessários para a interface SelectNativeProps tipando com React.FC para inferir o tipo da prop options e da prop type.

2021-07-06 17:37 UTC, dennervidal requested changes

2021-07-06 17:37 UTC, dennervidal commented on packages/kitchensink-app/storybook/stories/Select/Select.stories.tsx
> +const searchBar = <Input placeholder={'Busque a opção desejada'} />;
remover essa variavel não utilizada

2021-07-06 17:37 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +        <SearchBarContainer>
adicionar prop para controlar input opcional ou não

2021-07-06 17:41 UTC, dennervidal requested changes

2021-07-06 17:41 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Select/Modal.tsx
> +          <Text fontColor={'light'}>Confirmar</Text>
label parametrizavel

2021-07-07 14:06 UTC, dennervidal approved these changes

2021-07-07 14:06 UTC, dennervidal commented
@nilson-antonio @agnaldocitadin correções realizadas, realizando merge

2021-07-07 14:07 UTC, merged