Added Tabs Component to react-native-kit
tecsinapse/design-system pull request #17
Opened 2021-06-30 13:43 UTC by heliohfs

2021-06-30 14:00 UTC, dennervidal commented
só precisamos alinhar esse nome, me deu a impressão que eram as abas mesmo e não a navegação

2021-06-30 14:02 UTC, heliohfs commented
> só precisamos alinhar esse nome, me deu a impressão que eram as abas mesmo e não a navegação

Me baseei na nomenclatura do react-navigation

2021-06-30 17:07 UTC, agnaldocitadin commented on packages/react-native-kit/src/components/atoms/Tabs/Tab.tsx
> +      {...(_selected
Essas condições do _selected não seria melhor fazer fora do return?

2021-07-01 12:29 UTC, heliohfs commented on packages/react-native-kit/src/components/atoms/Tabs/Tab.tsx
> +      {...(_selected
Feito.

2021-07-06 18:24 UTC, dennervidal requested changes

2021-07-06 18:24 UTC, dennervidal commented on packages/kitchensink-app/storybook/stories/Tabs/Tabs.stories.tsx
> +        icon={{
Minha sugestão: receber o conteúdo das tabs via children, para flexibilizar o conteúdo renderizado.

Aguardar próximas opniões. @nilson-antonio @agnaldocitadin

2021-07-06 18:24 UTC, dennervidal commented on packages/react-native-kit/src/components/atoms/Tabs/styled.ts
> +  background-color: white;
trocar por miscellaneous.surfaceColor (#fff)

2021-07-09 16:49 UTC, agnaldocitadin approved these changes

2021-07-09 16:53 UTC, merged