Avatar
tecsinapse/design-system pull request #20
Opened 2021-07-07 18:12 UTC by ryancarloscorrea

Componente de avatar implementado.

2021-07-08 14:45 UTC, dennervidal requested changes

2021-07-08 14:45 UTC, dennervidal commented on packages/react-core/src/components/atoms/Avatar/styled.ts
> +  border-radius: 16px;
adotar o pill como radius tambem

2021-07-08 14:45 UTC, dennervidal commented on packages/react-core/src/components/atoms/Avatar/Avatar.tsx
> +        <StyledAvatar source={{ uri: srcImage }} />
chegou a testar com imagens retangulares? não que seja um problema, só pra saber mesmo

2021-07-08 14:45 UTC, dennervidal commented on packages/react-core/src/components/atoms/Avatar/Avatar.tsx
> +        <StyledAvatar source={{ uri: srcImage }} />
Outra coisa também, caso eu queira passar um require ou import (asset local), funciona? https://reactnative.dev/docs/image#examples

entendi que por hora só funciona com URL

2021-07-08 14:46 UTC, dennervidal commented
talvez seria interessante darmos acesso as props da image, mas podemos discutir, pois tem opções de caching

2021-07-09 15:07 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Avatar/styled.ts
> +  border-radius: 16px;
feito.

2021-07-09 15:41 UTC, ryancarloscorrea commented on packages/react-core/src/components/atoms/Avatar/Avatar.tsx
> +        <StyledAvatar source={{ uri: srcImage }} />
Testei agora, tirei um estilo e ta funcionando ok.

2021-07-09 19:08 UTC, merged