Componente ProgressBar e GroupButton
tecsinapse/design-system pull request #206
Opened 2024-06-19 18:58 UTC by ryancarloscorrea

2024-06-20 21:11 UTC, lucaspr98 requested changes

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/components/GroupButton.tsx
> +    groupButton();
passar para fora do corpo do componente

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/components/GroupButton.tsx
> +            )}
algum motivo para usar clsx ao invés de variantes?
Por exemplo, me parece que os estilos active e inactive podia ser uma variante de button? 

Até diria que o mesmo vale para firstButton e lastButton mas esses eu não entendi para que servem direito, então pode ser que faça sentido aqui.

Outro ponto, acho que eu usaria boolean ao invés de string em alguns desses casos, por exemplo, inactive, active e disabled.

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/components/GroupButton.tsx
> +  renderKey: (option?: T) => string | number | undefined;
faz sentido permitir que renderKey receba uma option opcional e retorna undefined?

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/components/ProgressBar.tsx
> +        };
Eu extrairia progressStyle e styleRadius para funções com useCallback

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/styles/groupButton.ts
> +    active: 'text-white bg-secondary-medium',
Aqui vai de encontro com o que comentei no GroupButton, de usar variantes, parece que faz sentido

2024-06-20 21:11 UTC, lucaspr98 commented on packages/cortex-react/src/styles/index.ts
> +export * from './progressBar';
exportar groupButton também

2024-06-21 13:37 UTC, ryancarloscorrea commented on packages/cortex-react/src/components/GroupButton.tsx
> +  renderKey: (option?: T) => string | number | undefined;
Eu tinha copiado da interface do web-kit, seguindo a recomendação do Denner, mas acho que não faz sentido, vou remover

2024-06-21 13:48 UTC, ryancarloscorrea commented on packages/cortex-react/src/styles/groupButton.ts
> +    active: 'text-white bg-secondary-medium',
analisando

2024-06-21 13:55 UTC, ryancarloscorrea commented on packages/cortex-react/src/components/GroupButton.tsx
> +            )}
Outro ponto que acabei de ver, se eu usar variants:
`export const groupButtonVariants = tv({
  base: 'border-[1px] border-secondary-medium px-centi py-mili items-center flex text-sub font-bold',
  variants: {
    inactive: {
      true: "bg-white text-secondary-medium disabled:bg-secondary-light'",
    },
    firstButton: {
      true: 'first:rounded-l-mili first:border-r-0',
    },
    lastButton: {
      true: 'last:rounded-r-mili last:border-l-0',
    },
    active: {
      true: 'text-white bg-secondary-medium',
    },
  },
});
`

Eu não consegueria dar liberdade pro dev passar estilos específicos para cada caso (first, last, active, inactive), ele teria opçãp de somente passar um className mais generico

2024-06-24 18:29 UTC, lucaspr98 approved these changes

2024-06-24 18:42 UTC, merged