feat(TS-6995): adição do componente tooltip e popover usando a lib fl…
tecsinapse/design-system pull request #212
Opened 2024-07-03 18:47 UTC by GabrielMaciel1

…oating-ui/react

2024-07-03 18:56 UTC, lucaspr98 requested changes
Achei a parte lógica do Tooltip e do Popover bem parecidas, acho que vale revisar e ver se é possível compartilhar de alguma maneira. 

Outra coisa que eu talvez tentaria fazer, seria usar composição no Popover, mais pelo fato de estar passando um content ReactNode para ele, acho que preferia que fosse via composição. Um exemplo disso é o Popover do radix:
https://www.radix-ui.com/themes/docs/components/popover

2024-07-03 18:56 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover.tsx
> +  };
Exportar para hook

2024-07-03 18:56 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover.tsx
> +      {isOpen && (
usar ternário

2024-07-03 18:56 UTC, lucaspr98 commented on packages/cortex-react/src/components/Tooltip.tsx
> +  };
exportar para hook

2024-07-03 18:56 UTC, lucaspr98 commented on packages/cortex-react/src/components/Tooltip.tsx
> +      {isOpen && (
usar ternário

2024-07-04 18:35 UTC, dennervidal requested changes

2024-07-04 18:35 UTC, dennervidal commented on packages/cortex-core/package.json
> +    "@popperjs/core": "^2.11.8",
precisa dessas dependencias aqui?

aparentemente não

2024-07-04 18:35 UTC, dennervidal commented on packages/cortex-react/docs/tooltip.stories.tsx
> +        tooltipText={args.tooltipText}
chamar só de `text`

2024-07-04 18:35 UTC, dennervidal commented on packages/cortex-react/src/components/Popover.tsx
> +          className={twMerge(
pq não usar `clsx`? ou usar o proprio variants

2024-07-04 18:35 UTC, dennervidal commented on packages/cortex-react/src/components/Popover.tsx
> +  content: React.ReactNode;
usar composição

2024-07-04 18:35 UTC, dennervidal commented on packages/cortex-react/src/components/Tooltip.tsx
> +  style?: React.CSSProperties;
precisa dessa prop aqui?

2024-07-04 18:40 UTC, GabrielMaciel1 commented on packages/cortex-core/package.json
> +    "@popperjs/core": "^2.11.8",
precisa mesmo não, era a que ia ser usada antes do floating-ui, vou remover

2024-07-04 18:41 UTC, GabrielMaciel1 commented on packages/cortex-react/src/components/Tooltip.tsx
> +  style?: React.CSSProperties;
não precisa, vou esta removendo

2024-07-04 18:43 UTC, dennervidal commented on packages/cortex-core/package.json
> +    "@popperjs/core": "^2.11.8",
beleza, até pq a segunda dep era react-popper, mesmo se fosse ela, deveria estar no outro pacote

2024-07-08 17:21 UTC, lucaspr98 requested changes

2024-07-08 17:21 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover/PopoverContext.tsx
> +  y?: number | null;
precisa desse null aqui?

2024-07-08 17:21 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover/PopoverContext.tsx
> +  const [trigger, setTrigger] = useState<'hover' | 'click'>('click');
Tem necessidade desses estados aqui? 
Não é mais fácil receber eles por props no PopoverProviderProps e depois só recuperar os valores placement e trigger nos componentes da composição que os utilizam?
Desse jeito ficou uns useEffects nos componentes que não sei se precisaria. 
Eu entendi a ideia, que nesse caso você passa o trigger pro componente trigger e o placement pro componente content. Mas, considerando que pro popover funcionar sempre vai precisar deles, não vejo problema em passar no Root

2024-07-08 17:21 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover/PopoverContent.tsx
> +  }, [placement, setPlacement]);
não sei se precisa do useEffect (ver comentário no context/provider)

2024-07-08 17:21 UTC, lucaspr98 commented on packages/cortex-react/src/components/Popover/PopoverTrigger.tsx
> +  }, [trigger, setTrigger]);
não sei se precisa do useEffect (ver comentário no context/provider)

2024-07-08 17:21 UTC, lucaspr98 commented on packages/cortex-react/src/tests/Popover.test.tsx
>    it('Should handle different placement values', async () => {
Achei esse teste um pouco grande, eu entendi ele mas fico na dúvida se não criar um para cada tipo de placement

2024-07-08 20:15 UTC, dennervidal requested changes

2024-07-08 20:15 UTC, dennervidal commented on packages/cortex-core/package.json
>      "react-popper": "^2.3.0",
faltou remover essa dep aqui

2024-07-09 14:31 UTC, lucaspr98 approved these changes

2024-07-09 18:00 UTC, merged