feat(TS-7559): adição do componente de uploader DS
tecsinapse/design-system pull request #255
Opened 2024-09-23 20:21 UTC by GabrielMaciel1

2024-09-23 20:33 UTC, lucaspr98 requested changes

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/index.ts
> +export * from './uploader';
Detalhe, nome do arquivo de componente com letra inicial em caixa alta: `Uploader`

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileDropzone.tsx
> +        <button className={button()}>Selecionar Arquivo</button>
Deixar esses valores customizáveis por prop. Não vejo problema deles serem opcionais e iniciarem com esses valores. Nesse caso, eu só deixaria em inglês os textos "default", só pra seguir o padrão dos outros textos default do cortex, que até onde me lembro estão em inglês.

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileDropzone.tsx
> +  dropzoneProps: any;
Talvez seria interessante criar um tipo para essa prop

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileUploadList.tsx
> +  files: { file: File; loading: 'loading' | 'success' | 'error' }[];
Só para fins de melhorar a leitura eu criaria um type pra isso, tipo FileUpload e aí `files: FileUpload[]`

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileUploadList.tsx
> +        </div>
Exportaria isso pra um outro componente. Por ex `FileUpload.tsx`

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileUploadList.tsx
> +        <h2 className="text-md font-semibold">Upload(s) em progresso</h2>
Mesmo comentário sobre o texto. Deixar uma prop opcional e setar default esse texto em inglês.

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/ModalUpload.tsx
> +        <h2 className="text-deca font-semibold">Upload de arquivos</h2>
Mesma questão do texto

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/uploader.tsx
> +  dropzoneProps: any;
Mesma coisa da tipagem

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/uploader.tsx
> +  files: { file: File; loading: 'loading' | 'success' | 'error' }[];
Mesma coisa do componente FileUploadList. Inclusive esse type FileUpload poderia estar em um arquivo types.ts  e esse e o outro arquivo puxarem o tipo dele

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/uploader.tsx
> +  files: { file: File; loading: 'loading' | 'success' | 'error' }[];
Inclusive, parece que já existe esse tipo FileItem no arquivo useFileUpload.

2024-09-23 20:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileUploadList.tsx
> +  files: { file: File; loading: 'loading' | 'success' | 'error' }[];
Inclusive, parece que já existe esse tipo FileItem no arquivo useFileUpload.

2024-09-24 13:41 UTC, lucaspr98 reviewed
Só mais um comentário para manter o padrão. Colocar primeira letra maíuscula na pasta e no arquivo uploader

2024-09-24 13:41 UTC, lucaspr98 commented on packages/cortex-react/src/components/uploader/FileUpload.tsx
> +            ✕
Aqui talvez seja melhor usar um ícone de botão?

2024-09-24 18:04 UTC, GabrielMaciel1 commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +      }, 2000);
Eu usei porque, dependendo do tamanho do arquivo, talvez nem houvesse carregamento. Então, para garantir pelo menos um feedback ao usuário, coloquei o timeout.

2024-09-25 20:00 UTC, lucaspr98 approved these changes

2024-09-26 13:29 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +      }, 2000);
eu acho que não precisa 
o que vcs acham @lucaspr98 @ryancarloscorrea

2024-09-26 13:35 UTC, lucaspr98 commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +      }, 2000);
é, eu não curto muito o uso de timeout pra feedbacks, prefiro evitar

2024-09-30 20:06 UTC, dennervidal requested changes

2024-09-30 20:06 UTC, dennervidal commented on packages/cortex-react/docs/uploader.stories.tsx
> +    console.log(files);
remover log

2024-09-30 20:06 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/types.ts
> +  // progress?: number;
pode remover essa prop comentada

2024-09-30 20:06 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/types.ts
> +  SUCCESS = 'success',
mudar para `{STATUS} = '{STATUS}'` (maiusculo)

2024-09-30 20:06 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +  minSize?: number;
minSize não precisa especificar

2024-09-30 20:10 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +    openModal,
mudar nomes das variaveis de retorno:
closeModal > onClose
openModal > onOpen

talvez não seria melhor criar apenas um `toggle` que alterna entre true e false? ou precisa de forma especifica onClose/onOpen?

deleteFile > onDelete
isOpen > open

2024-09-30 20:11 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/types.ts
> +  removeFile: (index: number) => void;
fileItem > file
removeFile > onDelete

tenta preservar o nome das properties entre os componentes, pra não virar confusão, tipo onRemove mudar pra onDelete do nada, ser consistente é importante

2024-09-30 20:12 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/types.ts
> +  isOpen: boolean;
convencionar nomes conforme outro comentário meu

2024-09-30 20:18 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +  IMAGE = 'image/*',
conforme meu outro comentário, ta duplicado essa questão do accept, bom deixar só um deles existir

2024-09-30 20:20 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +  // onDelete,
acho que seria bom deixar o onDelete opcional, vai que o dev quer um callback

poderia ser
`onDelete: (file: FileUpload<T>) => Promise<void>`

e na hora de clicar no X, chama a promise do onDelete se ela existir

2024-09-30 20:23 UTC, dennervidal commented
se possível revisem novamente
@ryancarloscorrea @lucaspr98

2024-09-30 20:43 UTC, lucaspr98 requested changes

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/FileDropzone.tsx
> +    >
Curiosidade, aqui faz diferença entre usar template string ao invés de utilizar clsx? Sinto que estávamos usando mais clsx como padrão quando o estilo necessitava de alguma condição

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/FileDropzone.tsx
> +          <p className="text-sm text-gray-500">{dropText}</p>
Utilizar algum type do cortex nessa cor, creio que o `text-secondary-medium` pode se assemelhar com esse

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/FileUpload.tsx
> +          {fileItem.file instanceof File &&
precisa desse instanceof? fileItem.file é sempre File, não?

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/FileUploadList.tsx
> +          key={index}
Talvez eu usaria `fileItem.file.uid` como `key`

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/ProgressBarInfinite.tsx
> +};
Dúvida para todos aqui @GabrielMaciel1 @dennervidal @ryancarloscorrea 
Chegou a ser discutido adicionar esse comportamento de "loading infinito" no componente ProgressBar que já existe? Se não, acham que seria interessante? Talvez como uma prop que adicione essa variante status no estilo do componente

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/types.ts
> +  titleModal?: string;
Acho uma boa idéia. Caso o dev queira só a dropzone por ex, aí ja vai pegar a file e fazer upload direto. As vezes nem precisa de tudo isso

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +  };
nada obrigatório, mas exportaria o que ta dentro do try e o que ta dentro do catch para duas funções com useCallback, só para melhorar a legibilidade da função onDrop. Acho que ela ficou um pouco grande

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +    openModal,
Dúvida Denner, mais sobre convenções. Você tem alguma opinião sobre usar **on**Func ou **handle**Func? 

Eu sinto que a gente costuma usar prefixo **on** quando estamos trabalhando com props e prefixo **handle** quando estamos trabalhando com funções "locais", que passamos na prop por ex. 

Nesse caso, o correto não seria **onOpen** e **onClose**? 

Só jogando essa discução aqui pra ver se chegamos em alguma padronização

2024-09-30 20:43 UTC, lucaspr98 commented on packages/cortex-react/src/tests/Uploader.test.tsx
> +});
Senti falta de alguns testes unitários dos componentes em si. FileDropzone, FileUpload, FileUploadList... 

Se os componentes "menores" já foram testados unitariamente, aqui só precisamos testar se as props estão sendo passadas corretamente e, se a integração entre eles está funcionando. Visto que não existe muita lógica no componente `Uploader`

Seguindo a lógica de testes unitários, creio que testar o Uploader seria testar se as props estão sendo passadas corretamente, se os componentes "menores" ja foram testados unitariamente. Aqui seria só o lugar

2024-09-30 21:08 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +    openModal,
Eu prefiro `on` por ser mais simples e direto "em" relação a alguma ação (ideia de callback)
`handle` me parece algo que vai ser manipulado, tipo `handleFile` (rotinas definidas)

2024-09-30 21:09 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/FileDropzone.tsx
> +    >
usar clsx

2024-09-30 21:09 UTC, dennervidal commented on packages/cortex-react/src/components/Uploader/ProgressBarInfinite.tsx
> +};
acho válido

2024-09-30 21:10 UTC, dennervidal commented on packages/cortex-react/src/hooks/useFileUpload.ts
> +  };
esse map mesmo tá igual nas duas situações, uma função mapToArray ja ajudaria

2024-10-09 13:04 UTC, lucaspr98 requested changes

2024-10-09 13:04 UTC, lucaspr98 commented on packages/cortex-react/src/styles/progressBar.ts
> +      uploading: '',
precisa disso?

2024-10-09 13:04 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/types.ts
> +  SUCCESS = 'success',
Acho que faltou atualizar aqui @GabrielMaciel1 
Ex 
```SUCCESS = 'SUCCESS'```

2024-10-09 17:28 UTC, GabrielMaciel1 commented on packages/cortex-react/src/styles/progressBar.ts
> +      uploading: '',
precisa, se nao ele reclama que ta faltando um type

2024-10-09 17:29 UTC, GabrielMaciel1 commented on packages/cortex-react/src/components/Uploader/types.ts
> +  SUCCESS = 'success',
@lucaspr98 nao mudei, pra ficar de acordo com o type que o progress aceita

```
intentProgress?:
    | 'default'
    | 'success'
    | 'warning'
    | 'info'
    | 'error'
    | 'uploading';
```

2024-10-09 17:31 UTC, dennervidal requested changes
acho bom tbm criar um wrapper q exporta a progress bar via composição

2024-10-09 17:31 UTC, dennervidal commented on packages/cortex-react/src/components/ProgressBar/ProgressBar.tsx
> +  valueMin?: number;
pq nao chamar só de max, min, current e intent?

2024-10-09 17:31 UTC, dennervidal commented on packages/cortex-react/src/components/ProgressBar/ProgressBarSegments.tsx
> +        transitionDelay: `${showAnimation ? `${index * 1000}ms` : `0ms`}`,
essas animações deviam ir pro tailwind eu acho, quase ctz q existem predefiniçoes

2024-10-09 17:33 UTC, lucaspr98 commented on packages/cortex-react/src/components/Uploader/types.ts
> +  SUCCESS = 'success',
Ah beleza @GabrielMaciel1 , só comentei porque no outro comentário do Denner acho que tava sem resposta. Mas entendi

2024-10-09 21:33 UTC, merged