feat(TS-7561): criação do componente Stepper
tecsinapse/design-system pull request #269
Opened 2024-10-22 17:28 UTC by GabrielMaciel1

2024-10-22 17:57 UTC, lucaspr98 requested changes

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/components/Stepper/Node.tsx
> +  children: React.ReactNode;
Adicionar um comentário  /** child element */ em cima do children, senão ele não aparece no Storybook

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/components/Stepper/Node.tsx
> +  onClick,
Como está usando o HTMLButtonElements, acho que pode remover o onClick daqui

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/components/Stepper/Node.tsx
> +    <button className={container()} onClick={onClick} {...rest}>
Aqui dois pontos:
1. Remover o onClick (considerando que já vai estar no rest)
2. className={container({ className })}  (igual outros exemplos do cortex-react, para mergear o classname que vem de cima)

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/components/Stepper/Node.tsx
> +      {segmented && <div className={separator()} />}
trocar && por ternário

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/components/Stepper/Root.tsx
> +        return null;
Exportaria tudo que está dentro do corpo do map para um memo no componente. Facilita a leitura do componente.

2024-10-22 17:57 UTC, lucaspr98 commented on packages/cortex-react/src/styles/stepNodeVariants.ts
> +    },
Dúvida, passando disabled true para o button, já não aplica isso?

2024-10-22 18:23 UTC, GabrielMaciel1 commented on packages/cortex-react/src/styles/stepNodeVariants.ts
> +    },
Não aplica tuco, ele fica disabled, mais nao com a aparência de disabled

2024-10-28 20:03 UTC, dennervidal requested changes

2024-10-28 20:03 UTC, dennervidal commented on packages/cortex-react/src/components/Stepper/Node.tsx
> +    <button className={container({ className })} {...rest}>
acho q faltou setar o `type='button'` aqui, nao?

2024-10-28 20:03 UTC, dennervidal commented on packages/cortex-react/src/components/Stepper/Root.tsx
> +  const handleNodeClick = (index: number, onClick?: () => void) => {
memoizar

2024-10-28 20:03 UTC, dennervidal commented on packages/cortex-react/src/components/Stepper/Root.tsx
> +  const childrenCount = React.Children.count(children);
acho q vale memoizar tbm

2024-11-01 13:38 UTC, dennervidal requested changes

2024-11-01 13:42 UTC, GabrielMaciel1 commented on .storybook/preview.tsx
> +  // <ThemeProvider theme={lightTheme}>
ja descomentei, e so uma erro que ta dando pra mim, ai subir sem querer

2024-11-04 13:00 UTC, dennervidal approved these changes

2024-11-04 17:41 UTC, merged