Breadcrumbs
tecsinapse/design-system pull request #40
Opened 2021-08-06 15:06 UTC by ryancarloscorrea

Componente de BreadCrumb adicionado.

2021-08-06 17:26 UTC, dennervidal requested changes

2021-08-06 17:26 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +            breadcrumbsLength={breadcrumbs.length}
se o lenght só é usado pra saber quando é o ultimo elemento, não é melhor criar um booleano `isLast={lenght -1 === index}`?

2021-08-06 17:26 UTC, dennervidal commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +const BreadCrumbs: FC<BreadCrumbsProps> = ({ breadcrumbs }) => {
renomear p/ `Breadcrumbs`, componente e tipagens

2021-08-10 18:44 UTC, ryancarloscorrea commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +            breadcrumbsLength={breadcrumbs.length}
faz sentido, vou alterar.

2021-08-10 18:44 UTC, ryancarloscorrea commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +const BreadCrumbs: FC<BreadCrumbsProps> = ({ breadcrumbs }) => {
ok

2021-08-12 14:11 UTC, ryancarloscorrea commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +            breadcrumbsLength={breadcrumbs.length}
feito.

2021-08-12 14:20 UTC, ryancarloscorrea commented on packages/react-web-kit/src/components/molecules/BreadCrumbs/BreadCrumbs.tsx
> +const BreadCrumbs: FC<BreadCrumbsProps> = ({ breadcrumbs }) => {
feito

2021-08-12 17:07 UTC, merged